name: main
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Run script file
      run: sh ./sample.sh
      
    - name: Run native script
      run: |
        echo nothing much
        ls -a
      
