name: main
on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: sh ./script.sh
